//
// Created by Andreas Braun on 28.11.2016.
//
#pragma once
#ifndef PATTERNRECOGNITION_UE4_ANDREASBRAUN_MARTINBRAUN_JULIANNEUBERGER_H
#define PATTERNRECOGNITION_UE4_ANDREASBRAUN_MARTINBRAUN_JULIANNEUBERGER_H

static void createRandomSamplesTriangle(){

}

#endif //PATTERNRECOGNITION_UE4_ANDREASBRAUN_MARTINBRAUN_JULIANNEUBERGER_H
